#pragma once
//**************************************
// lex.h
//
// Defines global symbols used the the flex generated lexer and 
// bison generated parser.
//
// Author: Anthony Jewell

#include "cSymbol.h"

// lexer function generated by flex
int yylex();

typedef struct
{
    cSymbol *symbol;
} yylval_t;

extern yylval_t yylval;
extern char *yytext;        // text of the current token
extern int yylineno;        // line number of current token
extern FILE *yyin;          // input file for lexer
extern int g_insert;        // global to indicate that symbols should be 
                            // inserted into the symbol table
extern int g_local;         // global to indicate to do local lookups
