#pragma once

// lexer function generated by flex
int yylex();
extern char *yytext;        // text of the current token
extern int yylineno;        // line number of current token
extern FILE *yyin;          // input file for lexer
